---
title: "Presentación"
author: "Tomás Bustos"

toc: false
---

# Mapas en acción: Análisis y visualización espacial con R

*Horario*: jueves 19hs / 2 horas de encuentro / 4 clases\
*Inicio tentativo:* 19 de febrero de 2026\
*Modalidad:* Encuentros en vivo / Clases grabadas y disponibles.\
*Docente:* Tomás Bustos.\
Más información en <https://cutt.ly/mapasenaccion> .

Expresá tus datos en mapas, combinando análisis espacial y visualización de información estadística. En este curso vamos a explorar cómo preparar datos geográficos, trabajar con polígonos, líneas y puntos, aplicar proyecciones cartográficas y diseñar mapas claros y expresivos con los paquetes más potentes del ecosistema de R. A lo largo de cuatro módulos, vas a crear productos visuales concretos: desde mapas coropléticos y de puntos hasta visualizaciones interactivas y análisis de autocorrelación espacial.

## Por qué un curso sobre mapas?

Porque comprender el territorio es clave para analizar fenómenos sociales, ambientales o económicos, y R ofrece herramientas potentes, abiertas y reproducibles para hacerlo sin depender de software propietario.

## Contenido

1.  **Introducción a toda marcha**

    -   Data: Manipulación de tablas con `tidyverse`.
    -   Viz: Visualización de información con `ggplot`.
    -   Data: Manipular información geográfica con `sf`.
    -   Producto: mapa de resultados para una fuerza.
    
2.  **Afinando las herramientas**

    -   Data: Operaciones complejas sobre tablas.
    -   Data: Operaciones espaciales para información geográfica.
    -   Viz: Visualización de información geográfica. Selección de paletas adecuadas.
    -   Producto: mapa de resultados con distintos recursos visuales (paletas secuenciales continuas y agrupadas, divergentes, categóricas).
    
3.  **Es más complejo**

    -   Viz: Complejizando la visualización de información geográfica: minimapas, mapas de fondo, mapas interactivos.
    -   Producto: Mapas bivariados.
    -   Viz: Visualizando otros objetos geográficos: puntos, líneas.
    -   Producto: partido ganador por sección. Cómo facilitar la interpretación.
    
4.  **Analítica avanzada**

    -   Data: cálculo de autocorrelación espacial global y local.
    -   Producto: mapa con resultados de autocorrelación espacial local.
